version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: boreas
    main: ./cmd/boreas
    binary: boreas
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64

dockers_v2:
  - id: boreas
    ids:
      - boreas
    images:
      - "ghcr.io/zenkiet/boreas"
    tags:
      - "{{ .Tag }}"
      - "latest"
      - "{{ .Major }}.{{ .Minor }}"
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: false
    flags:
      - "--provenance=false"

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: zenkiet
    name: boreas
  footer: >-

    ---

    Released by [ZenKiet](https://github.com/zenkiet).
