services:
  boreas-db:
    image: postgres:18-alpine
    container_name: boreas-db
    networks:
      - boreas-net
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${DATA_PATH:-./data}:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-boreas}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-boreas}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  boreas:
    # image: ghcr.io/boreas-ai/boreas:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: boreas
    ports:
      - "8080:8080"
    networks:
      - boreas-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BOREAS_DB_HOST: boreas-db
      BOREAS_DB_USER: ${POSTGRES_USER:-postgres}
      BOREAS_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      BOREAS_DB_NAME: ${POSTGRES_DB:-boreas}
      BOREAS_ADMIN_USERNAME: ${BOREAS_ADMIN_USERNAME:-admin}
      BOREAS_ADMIN_EMAIL: ${BOREAS_ADMIN_EMAIL:-admin@example.com}
      BOREAS_ADMIN_PASSWORD: ${BOREAS_ADMIN_PASSWORD:-LoveAngular123}
      BOREAS_NOTIFY_URL: ${BOREAS_NOTIFY_URL:-http://boreas-noti:8000/notify/boreas}
      BOREAS_FCM_PROJECT: ${BOREAS_FCM_PROJECT:-}
      BOREAS_FCM_KEYFILE: ${BOREAS_FCM_KEYFILE:-}
    depends_on:
      boreas-db:
        condition: service_healthy
    restart: ${RESTART_POLICY:-unless-stopped}

  boreas-noti:
    image: caronc/apprise:latest
    container_name: boreas-noti
    networks:
      - boreas-net
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: "1"
    volumes:
      - ${APPRISE_PATH:-./apprise}:/config
    restart: ${RESTART_POLICY:-unless-stopped}

networks:
  boreas-net:
    driver: bridge
